version: "3.9"

services:
  web:
    image: ghcr.io/django-graphQL
    volumes:
      - $PWD/media:/code/Django_graphQL_app/media
    ports:
      - "$PORT:8000"
    environment:
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_USER=$DATABASE_USER
      - SECRET_KEY=$SECRET_KEY
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_HOST=$DATABASE_HOST
      - FILE_STORAGE=$FILE_STORAGE
      - APP_URL=$APP_URL
      - ALLOWED_HOSTS=$ALLOWED_HOSTS
      - MEDIA_PATH=$MEDIA_PATH
    restart: always
