# Generated by Django 3.2.16 on 2022-10-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ripps_mismatch', models.CharField(blank=True, default='0', max_length=50)),
                ('ledger_mismatch', models.CharField(blank=True, default='0', max_length=50)),
                ('matching', models.CharField(blank=True, default='0', max_length=50)),
                ('ledger_mismatch_amount', models.CharField(blank=True, default='0', max_length=100)),
                ('ripps_mismatch_amount', models.CharField(blank=True, default='0', max_length=100)),
                ('match_amount', models.CharField(blank=True, default='0', max_length=100)),
                ('reconciled_file', models.CharField(blank=True, max_length=500)),
                ('ripps_date', models.CharField(blank=True, max_length=20)),
                ('report_type', models.CharField(blank=True, max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'recon_table',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('user_first_name', models.CharField(blank=True, max_length=40)),
                ('user_last_name', models.CharField(blank=True, max_length=40)),
                ('user_password', models.CharField(blank=True, max_length=200)),
                ('user_email', models.EmailField(blank=True, max_length=40)),
                ('user_status', models.CharField(blank=True, max_length=30)),
                ('user_phone_number', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
