# Generated by Django 3.2.16 on 2022-12-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_graphQL_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph_modal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=30)),
                ('user_name', models.CharField(blank=True, max_length=30)),
                ('user_first_name', models.CharField(blank=True, max_length=40)),
                ('user_last_name', models.CharField(blank=True, max_length=40)),
                ('user_email', models.EmailField(blank=True, max_length=40)),
                ('user_status', models.CharField(blank=True, max_length=30)),
                ('user_phone_number', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'db_table': 'graph_modal',
            },
        ),
        migrations.DeleteModel(
            name='ReconModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
